// <auto-generated />
#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Collections.Generic;

namespace DIGOS.Ambassador.Migrations
{
    public partial class ConfigureRoleplayParticipantRelationshipRequirements : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_RoleplayParticipant_Roleplays_RoleplayID",
                table: "RoleplayParticipant");

            migrationBuilder.DropForeignKey(
                name: "FK_RoleplayParticipant_Users_UserID",
                table: "RoleplayParticipant");

            migrationBuilder.AlterColumn<long>(
                name: "UserID",
                table: "RoleplayParticipant",
                nullable: false,
                oldClrType: typeof(long),
                oldNullable: true);

            migrationBuilder.AlterColumn<long>(
                name: "RoleplayID",
                table: "RoleplayParticipant",
                nullable: false,
                oldClrType: typeof(long),
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_RoleplayParticipant_Roleplays_RoleplayID",
                table: "RoleplayParticipant",
                column: "RoleplayID",
                principalTable: "Roleplays",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_RoleplayParticipant_Users_UserID",
                table: "RoleplayParticipant",
                column: "UserID",
                principalTable: "Users",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_RoleplayParticipant_Roleplays_RoleplayID",
                table: "RoleplayParticipant");

            migrationBuilder.DropForeignKey(
                name: "FK_RoleplayParticipant_Users_UserID",
                table: "RoleplayParticipant");

            migrationBuilder.AlterColumn<long>(
                name: "UserID",
                table: "RoleplayParticipant",
                nullable: true,
                oldClrType: typeof(long));

            migrationBuilder.AlterColumn<long>(
                name: "RoleplayID",
                table: "RoleplayParticipant",
                nullable: true,
                oldClrType: typeof(long));

            migrationBuilder.AddForeignKey(
                name: "FK_RoleplayParticipant_Roleplays_RoleplayID",
                table: "RoleplayParticipant",
                column: "RoleplayID",
                principalTable: "Roleplays",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_RoleplayParticipant_Users_UserID",
                table: "RoleplayParticipant",
                column: "UserID",
                principalTable: "Users",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
