// <auto-generated />
#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective
using Microsoft.EntityFrameworkCore.Migrations;

namespace DIGOS.Ambassador.Migrations
{
    public partial class FixIntermediatePermissionTableNames : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_LocalPermissionsIntermediateTableName",
                schema: "PermissionModule",
                table: "LocalPermissionsIntermediateTableName");

            migrationBuilder.DropPrimaryKey(
                name: "PK_GlobalPermissionsIntermediateTableName",
                schema: "PermissionModule",
                table: "GlobalPermissionsIntermediateTableName");

            migrationBuilder.RenameTable(
                name: "LocalPermissionsIntermediateTableName",
                schema: "PermissionModule",
                newName: "LocalPermissions",
                newSchema: "PermissionModule");

            migrationBuilder.RenameTable(
                name: "GlobalPermissionsIntermediateTableName",
                schema: "PermissionModule",
                newName: "GlobalPermissions",
                newSchema: "PermissionModule");

            migrationBuilder.AddPrimaryKey(
                name: "PK_LocalPermissions",
                schema: "PermissionModule",
                table: "LocalPermissions",
                column: "ID");

            migrationBuilder.AddPrimaryKey(
                name: "PK_GlobalPermissions",
                schema: "PermissionModule",
                table: "GlobalPermissions",
                column: "ID");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_LocalPermissions",
                schema: "PermissionModule",
                table: "LocalPermissions");

            migrationBuilder.DropPrimaryKey(
                name: "PK_GlobalPermissions",
                schema: "PermissionModule",
                table: "GlobalPermissions");

            migrationBuilder.RenameTable(
                name: "LocalPermissions",
                schema: "PermissionModule",
                newName: "LocalPermissionsIntermediateTableName",
                newSchema: "PermissionModule");

            migrationBuilder.RenameTable(
                name: "GlobalPermissions",
                schema: "PermissionModule",
                newName: "GlobalPermissionsIntermediateTableName",
                newSchema: "PermissionModule");

            migrationBuilder.AddPrimaryKey(
                name: "PK_LocalPermissionsIntermediateTableName",
                schema: "PermissionModule",
                table: "LocalPermissionsIntermediateTableName",
                column: "ID");

            migrationBuilder.AddPrimaryKey(
                name: "PK_GlobalPermissionsIntermediateTableName",
                schema: "PermissionModule",
                table: "GlobalPermissionsIntermediateTableName",
                column: "ID");
        }
    }
}
