// <auto-generated />
#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective
using Microsoft.EntityFrameworkCore.Migrations;

namespace DIGOS.Ambassador.Migrations
{
    public partial class RequireAppearanceComponentsToHaveTransformations : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_AppearanceComponent_Transformations_TransformationID",
                table: "AppearanceComponent");

            migrationBuilder.AlterColumn<long>(
                name: "TransformationID",
                table: "AppearanceComponent",
                nullable: false,
                oldClrType: typeof(long),
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_AppearanceComponent_Transformations_TransformationID",
                table: "AppearanceComponent",
                column: "TransformationID",
                principalTable: "Transformations",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_AppearanceComponent_Transformations_TransformationID",
                table: "AppearanceComponent");

            migrationBuilder.AlterColumn<long>(
                name: "TransformationID",
                table: "AppearanceComponent",
                nullable: true,
                oldClrType: typeof(long));

            migrationBuilder.AddForeignKey(
                name: "FK_AppearanceComponent_Transformations_TransformationID",
                table: "AppearanceComponent",
                column: "TransformationID",
                principalTable: "Transformations",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
