// <auto-generated />
#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective
using Microsoft.EntityFrameworkCore.Migrations;

namespace DIGOS.Ambassador.Migrations
{
    public partial class MoveAppearanceEntitiesToCorrectSchema : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_AppearanceComponent_Appearance_AppearanceID",
                table: "AppearanceComponent");

            migrationBuilder.DropForeignKey(
                name: "FK_AppearanceComponent_Colour_BaseColourID",
                table: "AppearanceComponent");

            migrationBuilder.DropForeignKey(
                name: "FK_AppearanceComponent_Colour_PatternColourID",
                table: "AppearanceComponent");

            migrationBuilder.DropForeignKey(
                name: "FK_AppearanceComponent_Transformations_TransformationID",
                table: "AppearanceComponent");

            migrationBuilder.DropForeignKey(
                name: "FK_Characters_Appearance_CurrentAppearanceID",
                table: "Characters");

            migrationBuilder.DropForeignKey(
                name: "FK_Characters_Appearance_DefaultAppearanceID",
                table: "Characters");

            migrationBuilder.DropForeignKey(
                name: "FK_Transformations_Colour_DefaultBaseColourID",
                schema: "TransformationModule",
                table: "Transformations");

            migrationBuilder.DropForeignKey(
                name: "FK_Transformations_Colour_DefaultPatternColourID",
                schema: "TransformationModule",
                table: "Transformations");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Colour",
                table: "Colour");

            migrationBuilder.DropPrimaryKey(
                name: "PK_AppearanceComponent",
                table: "AppearanceComponent");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Appearance",
                table: "Appearance");

            migrationBuilder.RenameTable(
                name: "Colour",
                newName: "Colours",
                newSchema: "TransformationModule");

            migrationBuilder.RenameTable(
                name: "AppearanceComponent",
                newName: "AppearanceComponents",
                newSchema: "TransformationModule");

            migrationBuilder.RenameTable(
                name: "Appearance",
                newName: "Appearances",
                newSchema: "TransformationModule");

            migrationBuilder.RenameIndex(
                name: "IX_AppearanceComponent_TransformationID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "IX_AppearanceComponents_TransformationID");

            migrationBuilder.RenameIndex(
                name: "IX_AppearanceComponent_PatternColourID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "IX_AppearanceComponents_PatternColourID");

            migrationBuilder.RenameIndex(
                name: "IX_AppearanceComponent_BaseColourID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "IX_AppearanceComponents_BaseColourID");

            migrationBuilder.RenameIndex(
                name: "IX_AppearanceComponent_AppearanceID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "IX_AppearanceComponents_AppearanceID");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Colours",
                schema: "TransformationModule",
                table: "Colours",
                column: "ID");

            migrationBuilder.AddPrimaryKey(
                name: "PK_AppearanceComponents",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                column: "ID");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Appearances",
                schema: "TransformationModule",
                table: "Appearances",
                column: "ID");

            migrationBuilder.AddForeignKey(
                name: "FK_Characters_Appearances_CurrentAppearanceID",
                table: "Characters",
                column: "CurrentAppearanceID",
                principalSchema: "TransformationModule",
                principalTable: "Appearances",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Characters_Appearances_DefaultAppearanceID",
                table: "Characters",
                column: "DefaultAppearanceID",
                principalSchema: "TransformationModule",
                principalTable: "Appearances",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_AppearanceComponents_Appearances_AppearanceID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                column: "AppearanceID",
                principalSchema: "TransformationModule",
                principalTable: "Appearances",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_AppearanceComponents_Colours_BaseColourID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                column: "BaseColourID",
                principalSchema: "TransformationModule",
                principalTable: "Colours",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_AppearanceComponents_Colours_PatternColourID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                column: "PatternColourID",
                principalSchema: "TransformationModule",
                principalTable: "Colours",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_AppearanceComponents_Transformations_TransformationID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                column: "TransformationID",
                principalSchema: "TransformationModule",
                principalTable: "Transformations",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Transformations_Colours_DefaultBaseColourID",
                schema: "TransformationModule",
                table: "Transformations",
                column: "DefaultBaseColourID",
                principalSchema: "TransformationModule",
                principalTable: "Colours",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Transformations_Colours_DefaultPatternColourID",
                schema: "TransformationModule",
                table: "Transformations",
                column: "DefaultPatternColourID",
                principalSchema: "TransformationModule",
                principalTable: "Colours",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Characters_Appearances_CurrentAppearanceID",
                table: "Characters");

            migrationBuilder.DropForeignKey(
                name: "FK_Characters_Appearances_DefaultAppearanceID",
                table: "Characters");

            migrationBuilder.DropForeignKey(
                name: "FK_AppearanceComponents_Appearances_AppearanceID",
                schema: "TransformationModule",
                table: "AppearanceComponents");

            migrationBuilder.DropForeignKey(
                name: "FK_AppearanceComponents_Colours_BaseColourID",
                schema: "TransformationModule",
                table: "AppearanceComponents");

            migrationBuilder.DropForeignKey(
                name: "FK_AppearanceComponents_Colours_PatternColourID",
                schema: "TransformationModule",
                table: "AppearanceComponents");

            migrationBuilder.DropForeignKey(
                name: "FK_AppearanceComponents_Transformations_TransformationID",
                schema: "TransformationModule",
                table: "AppearanceComponents");

            migrationBuilder.DropForeignKey(
                name: "FK_Transformations_Colours_DefaultBaseColourID",
                schema: "TransformationModule",
                table: "Transformations");

            migrationBuilder.DropForeignKey(
                name: "FK_Transformations_Colours_DefaultPatternColourID",
                schema: "TransformationModule",
                table: "Transformations");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Colours",
                schema: "TransformationModule",
                table: "Colours");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Appearances",
                schema: "TransformationModule",
                table: "Appearances");

            migrationBuilder.DropPrimaryKey(
                name: "PK_AppearanceComponents",
                schema: "TransformationModule",
                table: "AppearanceComponents");

            migrationBuilder.RenameTable(
                name: "Colours",
                schema: "TransformationModule",
                newName: "Colour");

            migrationBuilder.RenameTable(
                name: "Appearances",
                schema: "TransformationModule",
                newName: "Appearance");

            migrationBuilder.RenameTable(
                name: "AppearanceComponents",
                schema: "TransformationModule",
                newName: "AppearanceComponent");

            migrationBuilder.RenameIndex(
                name: "IX_AppearanceComponents_TransformationID",
                table: "AppearanceComponent",
                newName: "IX_AppearanceComponent_TransformationID");

            migrationBuilder.RenameIndex(
                name: "IX_AppearanceComponents_PatternColourID",
                table: "AppearanceComponent",
                newName: "IX_AppearanceComponent_PatternColourID");

            migrationBuilder.RenameIndex(
                name: "IX_AppearanceComponents_BaseColourID",
                table: "AppearanceComponent",
                newName: "IX_AppearanceComponent_BaseColourID");

            migrationBuilder.RenameIndex(
                name: "IX_AppearanceComponents_AppearanceID",
                table: "AppearanceComponent",
                newName: "IX_AppearanceComponent_AppearanceID");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Colour",
                table: "Colour",
                column: "ID");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Appearance",
                table: "Appearance",
                column: "ID");

            migrationBuilder.AddPrimaryKey(
                name: "PK_AppearanceComponent",
                table: "AppearanceComponent",
                column: "ID");

            migrationBuilder.AddForeignKey(
                name: "FK_AppearanceComponent_Appearance_AppearanceID",
                table: "AppearanceComponent",
                column: "AppearanceID",
                principalTable: "Appearance",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_AppearanceComponent_Colour_BaseColourID",
                table: "AppearanceComponent",
                column: "BaseColourID",
                principalTable: "Colour",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_AppearanceComponent_Colour_PatternColourID",
                table: "AppearanceComponent",
                column: "PatternColourID",
                principalTable: "Colour",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_AppearanceComponent_Transformations_TransformationID",
                table: "AppearanceComponent",
                column: "TransformationID",
                principalSchema: "TransformationModule",
                principalTable: "Transformations",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Characters_Appearance_CurrentAppearanceID",
                table: "Characters",
                column: "CurrentAppearanceID",
                principalTable: "Appearance",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Characters_Appearance_DefaultAppearanceID",
                table: "Characters",
                column: "DefaultAppearanceID",
                principalTable: "Appearance",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Transformations_Colour_DefaultBaseColourID",
                schema: "TransformationModule",
                table: "Transformations",
                column: "DefaultBaseColourID",
                principalTable: "Colour",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Transformations_Colour_DefaultPatternColourID",
                schema: "TransformationModule",
                table: "Transformations",
                column: "DefaultPatternColourID",
                principalTable: "Colour",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
