// <auto-generated />
#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective
using Microsoft.EntityFrameworkCore.Migrations;

namespace DIGOS.Ambassador.Migrations
{
    public partial class AddUniformTFMessages : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "UniformGrowMessage",
                table: "Transformations",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "UniformShiftMessage",
                table: "Transformations",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "UniformGrowMessage",
                table: "Transformations");

            migrationBuilder.DropColumn(
                name: "UniformShiftMessage",
                table: "Transformations");
        }
    }
}
