// <auto-generated />
#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DIGOS.Ambassador.Plugins.Transformations.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class RemoveAppearanceConfiguration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AppearanceConfigurations",
                schema: "TransformationModule");

            migrationBuilder.AddColumn<long>(
                name: "CharacterID",
                schema: "TransformationModule",
                table: "Appearances",
                nullable: false,
                defaultValue: 0L);

            migrationBuilder.AddColumn<bool>(
                name: "IsCurrent",
                schema: "TransformationModule",
                table: "Appearances",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDefault",
                schema: "TransformationModule",
                table: "Appearances",
                nullable: false,
                defaultValue: false);

            migrationBuilder.CreateIndex(
                name: "IX_Appearances_CharacterID",
                schema: "TransformationModule",
                table: "Appearances",
                column: "CharacterID");

            migrationBuilder.AddForeignKey(
                name: "FK_Appearances_Characters_CharacterID",
                schema: "TransformationModule",
                table: "Appearances",
                column: "CharacterID",
                principalSchema: "CharacterModule",
                principalTable: "Characters",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Appearances_Characters_CharacterID",
                schema: "TransformationModule",
                table: "Appearances");

            migrationBuilder.DropIndex(
                name: "IX_Appearances_CharacterID",
                schema: "TransformationModule",
                table: "Appearances");

            migrationBuilder.DropColumn(
                name: "CharacterID",
                schema: "TransformationModule",
                table: "Appearances");

            migrationBuilder.DropColumn(
                name: "IsCurrent",
                schema: "TransformationModule",
                table: "Appearances");

            migrationBuilder.DropColumn(
                name: "IsDefault",
                schema: "TransformationModule",
                table: "Appearances");

            migrationBuilder.CreateTable(
                name: "AppearanceConfigurations",
                schema: "TransformationModule",
                columns: table => new
                {
                    ID = table.Column<long>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn),
                    CharacterID = table.Column<long>(nullable: false),
                    CurrentAppearanceID = table.Column<long>(nullable: false),
                    DefaultAppearanceID = table.Column<long>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppearanceConfigurations", x => x.ID);
                    table.ForeignKey(
                        name: "FK_AppearanceConfigurations_Characters_CharacterID",
                        column: x => x.CharacterID,
                        principalSchema: "CharacterModule",
                        principalTable: "Characters",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AppearanceConfigurations_Appearances_CurrentAppearanceID",
                        column: x => x.CurrentAppearanceID,
                        principalSchema: "TransformationModule",
                        principalTable: "Appearances",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AppearanceConfigurations_Appearances_DefaultAppearanceID",
                        column: x => x.DefaultAppearanceID,
                        principalSchema: "TransformationModule",
                        principalTable: "Appearances",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AppearanceConfigurations_CharacterID",
                schema: "TransformationModule",
                table: "AppearanceConfigurations",
                column: "CharacterID");

            migrationBuilder.CreateIndex(
                name: "IX_AppearanceConfigurations_CurrentAppearanceID",
                schema: "TransformationModule",
                table: "AppearanceConfigurations",
                column: "CurrentAppearanceID");

            migrationBuilder.CreateIndex(
                name: "IX_AppearanceConfigurations_DefaultAppearanceID",
                schema: "TransformationModule",
                table: "AppearanceConfigurations",
                column: "DefaultAppearanceID");
        }
    }
}
