// <auto-generated />
#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DIGOS.Ambassador.Plugins.Transformations.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class CascadeComponentDeletions : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_AppearanceComponents_Appearances_AppearanceID",
                schema: "TransformationModule",
                table: "AppearanceComponents");

            migrationBuilder.AddForeignKey(
                name: "FK_AppearanceComponents_Appearances_AppearanceID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                column: "AppearanceID",
                principalSchema: "TransformationModule",
                principalTable: "Appearances",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_AppearanceComponents_Appearances_AppearanceID",
                schema: "TransformationModule",
                table: "AppearanceComponents");

            migrationBuilder.AddForeignKey(
                name: "FK_AppearanceComponents_Appearances_AppearanceID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                column: "AppearanceID",
                principalSchema: "TransformationModule",
                principalTable: "Appearances",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
