// <auto-generated />

#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective

using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DIGOS.Ambassador.Plugins.Transformations.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class UseSnakeCase : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"AppearanceComponents\" RENAME CONSTRAINT \"FK_AppearanceComponents_Appearances_AppearanceID\" to \"fk_appearance_components_appearances_appearance_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"AppearanceComponents\" RENAME CONSTRAINT \"FK_AppearanceComponents_Transformations_TransformationID\" to \"fk_appearance_components_transformations_transformation_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"Appearances\" RENAME CONSTRAINT \"FK_Appearances_Characters_CharacterID\" to \"fk_appearances_characters_character_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"BaseColours\" RENAME CONSTRAINT \"FK_BaseColours_AppearanceComponents_AppearanceComponentID\" to \"fk_base_colours_appearance_components_appearance_id_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"DefaultBaseColours\" RENAME CONSTRAINT \"FK_DefaultBaseColours_Transformations_TransformationID\" to \"fk_default_base_colours_transformations_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"DefaultPatternColours\" RENAME CONSTRAINT \"FK_DefaultPatternColours_Transformations_TransformationID\" to \"fk_default_pattern_colours_transformations_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"GlobalUserProtections\" RENAME CONSTRAINT \"FK_GlobalUserProtections_Users_UserID\" to \"fk_global_user_protections_users_user_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"PatternColours\" RENAME CONSTRAINT \"FK_PatternColours_AppearanceComponents_AppearanceComponentID\" to \"fk_pattern_colours_appearance_components_appearance_id_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"ServerUserProtections\" RENAME CONSTRAINT \"FK_ServerUserProtections_Servers_ServerID\" to \"fk_server_user_protections_servers_server_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"ServerUserProtections\" RENAME CONSTRAINT \"FK_ServerUserProtections_Users_UserID\" to \"fk_server_user_protections_users_user_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"Species\" RENAME CONSTRAINT \"FK_Species_Species_ParentID\" to \"fk_species_species_parent_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"Transformations\" RENAME CONSTRAINT \"FK_Transformations_Species_SpeciesID\" to \"fk_transformations_species_species_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"UserProtectionEntries\" RENAME CONSTRAINT \"FK_UserProtectionEntries_GlobalUserProtections_GlobalProtectio~\" to \"fk_user_protection_entries_global_user_protections_global_protectio\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"UserProtectionEntries\" RENAME CONSTRAINT \"FK_UserProtectionEntries_Users_UserID\" to \"fk_user_protection_entries_users_user_id\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"UserProtectionEntries\" RENAME CONSTRAINT \"PK_UserProtectionEntries\" to \"pk_user_protection_entries\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"Transformations\" RENAME CONSTRAINT \"PK_Transformations\" to \"pk_transformations\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"Species\" RENAME CONSTRAINT \"PK_Species\" to \"pk_species\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"ServerUserProtections\" RENAME CONSTRAINT \"PK_ServerUserProtections\" to \"pk_server_user_protections\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"GlobalUserProtections\" RENAME CONSTRAINT \"PK_GlobalUserProtections\" to \"pk_global_user_protections\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"DefaultPatternColours\" RENAME CONSTRAINT \"PK_DefaultPatternColours\" to \"pk_default_pattern_colours\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"DefaultBaseColours\" RENAME CONSTRAINT \"PK_DefaultBaseColours\" to \"pk_default_base_colours\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"Appearances\" RENAME CONSTRAINT \"PK_Appearances\" to \"pk_appearances\"");

            migrationBuilder.RenameColumn(
                name: "Type",
                schema: "TransformationModule",
                table: "UserProtectionEntries",
                newName: "type");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "TransformationModule",
                table: "UserProtectionEntries",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "UserID",
                schema: "TransformationModule",
                table: "UserProtectionEntries",
                newName: "user_id");

            migrationBuilder.RenameColumn(
                name: "GlobalProtectionID",
                schema: "TransformationModule",
                table: "UserProtectionEntries",
                newName: "global_protection_id");

            migrationBuilder.RenameIndex(
                name: "IX_UserProtectionEntries_UserID",
                schema: "TransformationModule",
                table: "UserProtectionEntries",
                newName: "ix_user_protection_entries_user_id");

            migrationBuilder.RenameIndex(
                name: "IX_UserProtectionEntries_GlobalProtectionID",
                schema: "TransformationModule",
                table: "UserProtectionEntries",
                newName: "ix_user_protection_entries_global_protection_id");

            migrationBuilder.RenameColumn(
                name: "Part",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "part");

            migrationBuilder.RenameColumn(
                name: "Description",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "description");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "UniformShiftMessage",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "uniform_shift_message");

            migrationBuilder.RenameColumn(
                name: "UniformGrowMessage",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "uniform_grow_message");

            migrationBuilder.RenameColumn(
                name: "UniformDescription",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "uniform_description");

            migrationBuilder.RenameColumn(
                name: "SpeciesID",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "species_id");

            migrationBuilder.RenameColumn(
                name: "SingleDescription",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "single_description");

            migrationBuilder.RenameColumn(
                name: "ShiftMessage",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "shift_message");

            migrationBuilder.RenameColumn(
                name: "IsNSFW",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "is_nsfw");

            migrationBuilder.RenameColumn(
                name: "GrowMessage",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "grow_message");

            migrationBuilder.RenameColumn(
                name: "DefaultPattern",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "default_pattern");

            migrationBuilder.RenameIndex(
                name: "IX_Transformations_SpeciesID",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "ix_transformations_species_id");

            migrationBuilder.RenameColumn(
                name: "Name",
                schema: "TransformationModule",
                table: "Species",
                newName: "name");

            migrationBuilder.RenameColumn(
                name: "Description",
                schema: "TransformationModule",
                table: "Species",
                newName: "description");

            migrationBuilder.RenameColumn(
                name: "Author",
                schema: "TransformationModule",
                table: "Species",
                newName: "author");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "TransformationModule",
                table: "Species",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "ParentID",
                schema: "TransformationModule",
                table: "Species",
                newName: "parent_id");

            migrationBuilder.RenameIndex(
                name: "IX_Species_ParentID",
                schema: "TransformationModule",
                table: "Species",
                newName: "ix_species_parent_id");

            migrationBuilder.RenameColumn(
                name: "Type",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "type");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "UserID",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "user_id");

            migrationBuilder.RenameColumn(
                name: "ServerID",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "server_id");

            migrationBuilder.RenameColumn(
                name: "HasOptedIn",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "has_opted_in");

            migrationBuilder.RenameIndex(
                name: "IX_ServerUserProtections_UserID",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "ix_server_user_protections_user_id");

            migrationBuilder.RenameIndex(
                name: "IX_ServerUserProtections_ServerID",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "ix_server_user_protections_server_id");

            migrationBuilder.RenameColumn(
                name: "Shade",
                schema: "TransformationModule",
                table: "PatternColours",
                newName: "shade");

            migrationBuilder.RenameColumn(
                name: "Modifier",
                schema: "TransformationModule",
                table: "PatternColours",
                newName: "modifier");

            migrationBuilder.RenameColumn(
                name: "AppearanceComponentID",
                schema: "TransformationModule",
                table: "PatternColours",
                newName: "appearance_component_id");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "TransformationModule",
                table: "GlobalUserProtections",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "UserID",
                schema: "TransformationModule",
                table: "GlobalUserProtections",
                newName: "user_id");

            migrationBuilder.RenameColumn(
                name: "DefaultType",
                schema: "TransformationModule",
                table: "GlobalUserProtections",
                newName: "default_type");

            migrationBuilder.RenameColumn(
                name: "DefaultOptIn",
                schema: "TransformationModule",
                table: "GlobalUserProtections",
                newName: "default_opt_in");

            migrationBuilder.RenameIndex(
                name: "IX_GlobalUserProtections_UserID",
                schema: "TransformationModule",
                table: "GlobalUserProtections",
                newName: "ix_global_user_protections_user_id");

            migrationBuilder.RenameColumn(
                name: "Shade",
                schema: "TransformationModule",
                table: "DefaultPatternColours",
                newName: "shade");

            migrationBuilder.RenameColumn(
                name: "Modifier",
                schema: "TransformationModule",
                table: "DefaultPatternColours",
                newName: "modifier");

            migrationBuilder.RenameColumn(
                name: "TransformationID",
                schema: "TransformationModule",
                table: "DefaultPatternColours",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "Shade",
                schema: "TransformationModule",
                table: "DefaultBaseColours",
                newName: "shade");

            migrationBuilder.RenameColumn(
                name: "Modifier",
                schema: "TransformationModule",
                table: "DefaultBaseColours",
                newName: "modifier");

            migrationBuilder.RenameColumn(
                name: "TransformationID",
                schema: "TransformationModule",
                table: "DefaultBaseColours",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "Shade",
                schema: "TransformationModule",
                table: "BaseColours",
                newName: "shade");

            migrationBuilder.RenameColumn(
                name: "Modifier",
                schema: "TransformationModule",
                table: "BaseColours",
                newName: "modifier");

            migrationBuilder.RenameColumn(
                name: "AppearanceComponentID",
                schema: "TransformationModule",
                table: "BaseColours",
                newName: "appearance_component_id");

            migrationBuilder.RenameColumn(
                name: "Weight",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "weight");

            migrationBuilder.RenameColumn(
                name: "Muscularity",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "muscularity");

            migrationBuilder.RenameColumn(
                name: "Height",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "height");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "IsDefault",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "is_default");

            migrationBuilder.RenameColumn(
                name: "IsCurrent",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "is_current");

            migrationBuilder.RenameColumn(
                name: "CharacterID",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "character_id");

            migrationBuilder.RenameIndex(
                name: "IX_Appearances_CharacterID",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "ix_appearances_character_id");

            migrationBuilder.RenameColumn(
                name: "Pattern",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "pattern");

            migrationBuilder.RenameColumn(
                name: "Chirality",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "chirality");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "TransformationID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "transformation_id");

            migrationBuilder.RenameColumn(
                name: "AppearanceID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "appearance_id");

            migrationBuilder.RenameIndex(
                name: "IX_AppearanceComponents_TransformationID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "ix_appearance_components_transformation_id");

            migrationBuilder.RenameIndex(
                name: "IX_AppearanceComponents_AppearanceID",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "ix_appearance_components_appearance_id");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"AppearanceComponents\" RENAME CONSTRAINT \"fk_appearance_components_appearances_appearance_id\" to \"FK_AppearanceComponents_Appearances_AppearanceID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"AppearanceComponents\" RENAME CONSTRAINT \"fk_appearance_components_transformations_transformation_id\" to \"FK_AppearanceComponents_Transformations_TransformationID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"Appearances\" RENAME CONSTRAINT \"fk_appearances_characters_character_id\" to \"FK_Appearances_Characters_CharacterID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"BaseColours\" RENAME CONSTRAINT \"fk_base_colours_appearance_components_appearance_id_id\" to \"FK_BaseColours_AppearanceComponents_AppearanceComponentID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"DefaultBaseColours\" RENAME CONSTRAINT \"fk_default_base_colours_transformations_id\" to \"FK_DefaultBaseColours_Transformations_TransformationID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"DefaultPatternColours\" RENAME CONSTRAINT \"fk_default_pattern_colours_transformations_id\" to \"FK_DefaultPatternColours_Transformations_TransformationID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"GlobalUserProtections\" RENAME CONSTRAINT \"fk_global_user_protections_users_user_id\" to \"FK_GlobalUserProtections_Users_UserID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"PatternColours\" RENAME CONSTRAINT \"fk_pattern_colours_appearance_components_appearance_id_id\" to \"FK_PatternColours_AppearanceComponents_AppearanceComponentID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"ServerUserProtections\" RENAME CONSTRAINT \"fk_server_user_protections_servers_server_id\" to \"FK_ServerUserProtections_Servers_ServerID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"ServerUserProtections\" RENAME CONSTRAINT \"fk_server_user_protections_users_user_id\" to \"FK_ServerUserProtections_Users_UserID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"Species\" RENAME CONSTRAINT \"fk_species_species_parent_id\" to \"FK_Species_Species_ParentID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"Transformations\" RENAME CONSTRAINT \"fk_transformations_species_species_id\" to \"FK_Transformations_Species_SpeciesID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"UserProtectionEntries\" RENAME CONSTRAINT \"fk_user_protection_entries_global_user_protections_global_protectio\" to \"FK_UserProtectionEntries_GlobalUserProtections_GlobalProtectio~\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"UserProtectionEntries\" RENAME CONSTRAINT \"fk_user_protection_entries_users_user_id\" to \"FK_UserProtectionEntries_Users_UserID\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"UserProtectionEntries\" RENAME CONSTRAINT \"pk_user_protection_entries\" to \"PK_UserProtectionEntries\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"Transformations\" RENAME CONSTRAINT \"pk_transformations\" to \"PK_Transformations\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"Species\" RENAME CONSTRAINT \"pk_species\" to \"PK_Species\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"ServerUserProtections\" RENAME CONSTRAINT \"pk_server_user_protections\" to \"PK_ServerUserProtections\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"GlobalUserProtections\" RENAME CONSTRAINT \"pk_global_user_protections\" to \"PK_GlobalUserProtections\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"DefaultPatternColours\" RENAME CONSTRAINT \"pk_default_pattern_colours\" to \"PK_DefaultPatternColours\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"DefaultBaseColours\" RENAME CONSTRAINT \"pk_default_base_colours\" to \"PK_DefaultBaseColours\"");

            migrationBuilder.Sql("ALTER TABLE \"TransformationModule\".\"Appearances\" RENAME CONSTRAINT \"pk_appearances\" to \"PK_Appearances\"");

            migrationBuilder.RenameColumn(
                name: "type",
                schema: "TransformationModule",
                table: "UserProtectionEntries",
                newName: "Type");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "TransformationModule",
                table: "UserProtectionEntries",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "user_id",
                schema: "TransformationModule",
                table: "UserProtectionEntries",
                newName: "UserID");

            migrationBuilder.RenameColumn(
                name: "global_protection_id",
                schema: "TransformationModule",
                table: "UserProtectionEntries",
                newName: "GlobalProtectionID");

            migrationBuilder.RenameIndex(
                name: "ix_user_protection_entries_user_id",
                schema: "TransformationModule",
                table: "UserProtectionEntries",
                newName: "IX_UserProtectionEntries_UserID");

            migrationBuilder.RenameIndex(
                name: "ix_user_protection_entries_global_protection_id",
                schema: "TransformationModule",
                table: "UserProtectionEntries",
                newName: "IX_UserProtectionEntries_GlobalProtectionID");

            migrationBuilder.RenameColumn(
                name: "part",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "Part");

            migrationBuilder.RenameColumn(
                name: "description",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "Description");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "uniform_shift_message",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "UniformShiftMessage");

            migrationBuilder.RenameColumn(
                name: "uniform_grow_message",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "UniformGrowMessage");

            migrationBuilder.RenameColumn(
                name: "uniform_description",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "UniformDescription");

            migrationBuilder.RenameColumn(
                name: "species_id",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "SpeciesID");

            migrationBuilder.RenameColumn(
                name: "single_description",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "SingleDescription");

            migrationBuilder.RenameColumn(
                name: "shift_message",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "ShiftMessage");

            migrationBuilder.RenameColumn(
                name: "is_nsfw",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "IsNSFW");

            migrationBuilder.RenameColumn(
                name: "grow_message",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "GrowMessage");

            migrationBuilder.RenameColumn(
                name: "default_pattern",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "DefaultPattern");

            migrationBuilder.RenameIndex(
                name: "ix_transformations_species_id",
                schema: "TransformationModule",
                table: "Transformations",
                newName: "IX_Transformations_SpeciesID");

            migrationBuilder.RenameColumn(
                name: "name",
                schema: "TransformationModule",
                table: "Species",
                newName: "Name");

            migrationBuilder.RenameColumn(
                name: "description",
                schema: "TransformationModule",
                table: "Species",
                newName: "Description");

            migrationBuilder.RenameColumn(
                name: "author",
                schema: "TransformationModule",
                table: "Species",
                newName: "Author");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "TransformationModule",
                table: "Species",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "parent_id",
                schema: "TransformationModule",
                table: "Species",
                newName: "ParentID");

            migrationBuilder.RenameIndex(
                name: "ix_species_parent_id",
                schema: "TransformationModule",
                table: "Species",
                newName: "IX_Species_ParentID");

            migrationBuilder.RenameColumn(
                name: "type",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "Type");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "user_id",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "UserID");

            migrationBuilder.RenameColumn(
                name: "server_id",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "ServerID");

            migrationBuilder.RenameColumn(
                name: "has_opted_in",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "HasOptedIn");

            migrationBuilder.RenameIndex(
                name: "ix_server_user_protections_user_id",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "IX_ServerUserProtections_UserID");

            migrationBuilder.RenameIndex(
                name: "ix_server_user_protections_server_id",
                schema: "TransformationModule",
                table: "ServerUserProtections",
                newName: "IX_ServerUserProtections_ServerID");

            migrationBuilder.RenameColumn(
                name: "shade",
                schema: "TransformationModule",
                table: "PatternColours",
                newName: "Shade");

            migrationBuilder.RenameColumn(
                name: "modifier",
                schema: "TransformationModule",
                table: "PatternColours",
                newName: "Modifier");

            migrationBuilder.RenameColumn(
                name: "appearance_component_id",
                schema: "TransformationModule",
                table: "PatternColours",
                newName: "AppearanceComponentID");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "TransformationModule",
                table: "GlobalUserProtections",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "user_id",
                schema: "TransformationModule",
                table: "GlobalUserProtections",
                newName: "UserID");

            migrationBuilder.RenameColumn(
                name: "default_type",
                schema: "TransformationModule",
                table: "GlobalUserProtections",
                newName: "DefaultType");

            migrationBuilder.RenameColumn(
                name: "default_opt_in",
                schema: "TransformationModule",
                table: "GlobalUserProtections",
                newName: "DefaultOptIn");

            migrationBuilder.RenameIndex(
                name: "ix_global_user_protections_user_id",
                schema: "TransformationModule",
                table: "GlobalUserProtections",
                newName: "IX_GlobalUserProtections_UserID");

            migrationBuilder.RenameColumn(
                name: "shade",
                schema: "TransformationModule",
                table: "DefaultPatternColours",
                newName: "Shade");

            migrationBuilder.RenameColumn(
                name: "modifier",
                schema: "TransformationModule",
                table: "DefaultPatternColours",
                newName: "Modifier");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "TransformationModule",
                table: "DefaultPatternColours",
                newName: "TransformationID");

            migrationBuilder.RenameColumn(
                name: "shade",
                schema: "TransformationModule",
                table: "DefaultBaseColours",
                newName: "Shade");

            migrationBuilder.RenameColumn(
                name: "modifier",
                schema: "TransformationModule",
                table: "DefaultBaseColours",
                newName: "Modifier");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "TransformationModule",
                table: "DefaultBaseColours",
                newName: "TransformationID");

            migrationBuilder.RenameColumn(
                name: "shade",
                schema: "TransformationModule",
                table: "BaseColours",
                newName: "Shade");

            migrationBuilder.RenameColumn(
                name: "modifier",
                schema: "TransformationModule",
                table: "BaseColours",
                newName: "Modifier");

            migrationBuilder.RenameColumn(
                name: "appearance_component_id",
                schema: "TransformationModule",
                table: "BaseColours",
                newName: "AppearanceComponentID");

            migrationBuilder.RenameColumn(
                name: "weight",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "Weight");

            migrationBuilder.RenameColumn(
                name: "muscularity",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "Muscularity");

            migrationBuilder.RenameColumn(
                name: "height",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "Height");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "is_default",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "IsDefault");

            migrationBuilder.RenameColumn(
                name: "is_current",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "IsCurrent");

            migrationBuilder.RenameColumn(
                name: "character_id",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "CharacterID");

            migrationBuilder.RenameIndex(
                name: "ix_appearances_character_id",
                schema: "TransformationModule",
                table: "Appearances",
                newName: "IX_Appearances_CharacterID");

            migrationBuilder.RenameColumn(
                name: "pattern",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "Pattern");

            migrationBuilder.RenameColumn(
                name: "chirality",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "Chirality");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "transformation_id",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "TransformationID");

            migrationBuilder.RenameColumn(
                name: "appearance_id",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "AppearanceID");

            migrationBuilder.RenameIndex(
                name: "ix_appearance_components_transformation_id",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "IX_AppearanceComponents_TransformationID");

            migrationBuilder.RenameIndex(
                name: "ix_appearance_components_appearance_id",
                schema: "TransformationModule",
                table: "AppearanceComponents",
                newName: "IX_AppearanceComponents_AppearanceID");
        }
    }
}
