// <auto-generated />

#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective

using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DIGOS.Ambassador.Plugins.Core.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class AddDiscordIDIndex : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Delete duplicate servers
            migrationBuilder.Sql
            (
                "delete from \"Core\".\"Servers\" where \"ID\" in (select \"ID\" from (select \"ID\", \"DiscordID\", row_number() over (partition by \"DiscordID\" order by \"ID\" asc) as Row from \"Core\".\"Servers\") dupes where dupes.Row > 1)\n"
            );

            // Delete duplicate users
            migrationBuilder.Sql
            (
                "delete from \"Core\".\"Users\" where \"ID\" in (select \"ID\" from (select \"ID\", \"DiscordID\", row_number() over (partition by \"DiscordID\" order by \"ID\" asc) as Row from \"Core\".\"Users\") dupes where dupes.Row > 1)\n"
            );

            migrationBuilder.CreateIndex(
                name: "IX_Users_DiscordID",
                schema: "Core",
                table: "Users",
                column: "DiscordID",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Servers_DiscordID",
                schema: "Core",
                table: "Servers",
                column: "DiscordID",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Users_DiscordID",
                schema: "Core",
                table: "Users");

            migrationBuilder.DropIndex(
                name: "IX_Servers_DiscordID",
                schema: "Core",
                table: "Servers");
        }
    }
}

