// <auto-generated />

#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective

using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DIGOS.Ambassador.Plugins.Core.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class UseSnakeCase : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql
            (
                "ALTER TABLE \"Core\".\"ServerUser\" RENAME CONSTRAINT \"FK_ServerUser_Servers_ServerID\" to fk_server_user_servers_server_id"
            );

            migrationBuilder.Sql
            (
                "ALTER TABLE \"Core\".\"ServerUser\" RENAME CONSTRAINT \"FK_ServerUser_Users_UserID\" to fk_server_user_users_user_id"
            );

            migrationBuilder.Sql
            (
                "ALTER TABLE \"Core\".\"ServerUser\" RENAME CONSTRAINT \"PK_ServerUser\" to pk_server_user"
            );

            migrationBuilder.Sql
            (
                "ALTER TABLE \"Core\".\"Users\" RENAME CONSTRAINT \"PK_Users\" to pk_users"
            );

            migrationBuilder.Sql
            (
                "ALTER TABLE \"Core\".\"UserConsents\" RENAME CONSTRAINT \"PK_UserConsents\" to pk_users_consents"
            );

            migrationBuilder.Sql
            (
                "ALTER TABLE \"Core\".\"Servers\" RENAME CONSTRAINT \"PK_Servers\" to pk_servers"
            );

            migrationBuilder.RenameColumn(
                name: "Timezone",
                schema: "Core",
                table: "Users",
                newName: "timezone");

            migrationBuilder.RenameColumn(
                name: "Bio",
                schema: "Core",
                table: "Users",
                newName: "bio");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "Core",
                table: "Users",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "DiscordID",
                schema: "Core",
                table: "Users",
                newName: "discord_id");

            migrationBuilder.RenameIndex(
                name: "IX_Users_DiscordID",
                schema: "Core",
                table: "Users",
                newName: "ix_users_discord_id");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "Core",
                table: "UserConsents",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "HasConsented",
                schema: "Core",
                table: "UserConsents",
                newName: "has_consented");

            migrationBuilder.RenameColumn(
                name: "DiscordID",
                schema: "Core",
                table: "UserConsents",
                newName: "discord_id");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "Core",
                table: "ServerUser",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "UserID",
                schema: "Core",
                table: "ServerUser",
                newName: "user_id");

            migrationBuilder.RenameColumn(
                name: "ServerID",
                schema: "Core",
                table: "ServerUser",
                newName: "server_id");

            migrationBuilder.RenameIndex(
                name: "IX_ServerUser_UserID",
                schema: "Core",
                table: "ServerUser",
                newName: "ix_server_user_user_id");

            migrationBuilder.RenameIndex(
                name: "IX_ServerUser_ServerID",
                schema: "Core",
                table: "ServerUser",
                newName: "ix_server_user_server_id");

            migrationBuilder.RenameColumn(
                name: "Description",
                schema: "Core",
                table: "Servers",
                newName: "description");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "Core",
                table: "Servers",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "SuppressPermissionWarnings",
                schema: "Core",
                table: "Servers",
                newName: "suppress_permission_warnings");

            migrationBuilder.RenameColumn(
                name: "SendJoinMessage",
                schema: "Core",
                table: "Servers",
                newName: "send_join_message");

            migrationBuilder.RenameColumn(
                name: "JoinMessage",
                schema: "Core",
                table: "Servers",
                newName: "join_message");

            migrationBuilder.RenameColumn(
                name: "IsNSFW",
                schema: "Core",
                table: "Servers",
                newName: "is_nsfw");

            migrationBuilder.RenameColumn(
                name: "DiscordID",
                schema: "Core",
                table: "Servers",
                newName: "discord_id");

            migrationBuilder.RenameIndex(
                name: "IX_Servers_DiscordID",
                schema: "Core",
                table: "Servers",
                newName: "ix_servers_discord_id");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql
            (
                "ALTER TABLE \"Core\".\"ServerUser\" RENAME CONSTRAINT fk_server_user_servers_server_id to \"FK_ServerUser_Servers_ServerID\""
            );

            migrationBuilder.Sql
            (
                "ALTER TABLE \"Core\".\"ServerUser\" RENAME CONSTRAINT fk_server_user_users_user_id to \"FK_ServerUser_Users_UserID\""
            );

            migrationBuilder.Sql
            (
                "ALTER TABLE \"Core\".\"ServerUser\" RENAME CONSTRAINT pk_server_user to \"PK_ServerUser\""
            );

            migrationBuilder.Sql
            (
                "ALTER TABLE \"Core\".\"Users\" RENAME CONSTRAINT pk_users to \"PK_Users\""
            );

            migrationBuilder.Sql
            (
                "ALTER TABLE \"Core\".\"UserConsents\" RENAME CONSTRAINT pk_users_consents to \"PK_UserConsents\""
            );

            migrationBuilder.Sql
            (
                "ALTER TABLE \"Core\".\"Servers\" RENAME CONSTRAINT pk_servers to \"PK_Servers\""
            );

            migrationBuilder.RenameColumn(
                name: "timezone",
                schema: "Core",
                table: "Users",
                newName: "Timezone");

            migrationBuilder.RenameColumn(
                name: "bio",
                schema: "Core",
                table: "Users",
                newName: "Bio");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "Core",
                table: "Users",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "discord_id",
                schema: "Core",
                table: "Users",
                newName: "DiscordID");

            migrationBuilder.RenameIndex(
                name: "ix_users_discord_id",
                schema: "Core",
                table: "Users",
                newName: "IX_Users_DiscordID");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "Core",
                table: "UserConsents",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "has_consented",
                schema: "Core",
                table: "UserConsents",
                newName: "HasConsented");

            migrationBuilder.RenameColumn(
                name: "discord_id",
                schema: "Core",
                table: "UserConsents",
                newName: "DiscordID");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "Core",
                table: "ServerUser",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "user_id",
                schema: "Core",
                table: "ServerUser",
                newName: "UserID");

            migrationBuilder.RenameColumn(
                name: "server_id",
                schema: "Core",
                table: "ServerUser",
                newName: "ServerID");

            migrationBuilder.RenameIndex(
                name: "ix_server_user_user_id",
                schema: "Core",
                table: "ServerUser",
                newName: "IX_ServerUser_UserID");

            migrationBuilder.RenameIndex(
                name: "ix_server_user_server_id",
                schema: "Core",
                table: "ServerUser",
                newName: "IX_ServerUser_ServerID");

            migrationBuilder.RenameColumn(
                name: "description",
                schema: "Core",
                table: "Servers",
                newName: "Description");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "Core",
                table: "Servers",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "suppress_permission_warnings",
                schema: "Core",
                table: "Servers",
                newName: "SuppressPermissionWarnings");

            migrationBuilder.RenameColumn(
                name: "send_join_message",
                schema: "Core",
                table: "Servers",
                newName: "SendJoinMessage");

            migrationBuilder.RenameColumn(
                name: "join_message",
                schema: "Core",
                table: "Servers",
                newName: "JoinMessage");

            migrationBuilder.RenameColumn(
                name: "is_nsfw",
                schema: "Core",
                table: "Servers",
                newName: "IsNSFW");

            migrationBuilder.RenameColumn(
                name: "discord_id",
                schema: "Core",
                table: "Servers",
                newName: "DiscordID");

            migrationBuilder.RenameIndex(
                name: "ix_servers_discord_id",
                schema: "Core",
                table: "Servers",
                newName: "IX_Servers_DiscordID");
        }
    }
}
