// <auto-generated />

#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective

using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DIGOS.Ambassador.Plugins.Moderation.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class UseSnakeCase : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"ServerModerationSettings\" RENAME CONSTRAINT \"FK_ServerModerationSettings_Servers_ServerID\" to \"fk_server_moderation_settings_servers_server_id\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserBans\" RENAME CONSTRAINT \"FK_UserBans_Servers_ServerID\" to \"fk_user_bans_servers_server_id\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserBans\" RENAME CONSTRAINT \"FK_UserBans_Users_AuthorID\" to \"fk_user_bans_users_author_id\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserBans\" RENAME CONSTRAINT \"FK_UserBans_Users_UserID\" to \"fk_user_bans_users_user_id\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserNotes\" RENAME CONSTRAINT \"FK_UserNotes_Servers_ServerID\" to \"fk_user_notes_servers_server_id\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserNotes\" RENAME CONSTRAINT \"FK_UserNotes_Users_AuthorID\" to \"fk_user_notes_users_author_id\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserNotes\" RENAME CONSTRAINT \"FK_UserNotes_Users_UserID\" to \"fk_user_notes_users_user_id\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserWarnings\" RENAME CONSTRAINT \"FK_UserWarnings_Servers_ServerID\" to \"fk_user_warnings_servers_server_id\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserWarnings\" RENAME CONSTRAINT \"FK_UserWarnings_Users_AuthorID\" to \"fk_user_warnings_users_author_id\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserWarnings\" RENAME CONSTRAINT \"FK_UserWarnings_Users_UserID\" to \"fk_user_warnings_users_user_id\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserWarnings\" RENAME CONSTRAINT \"PK_UserWarnings\" to \"pk_user_warnings\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserNotes\" RENAME CONSTRAINT \"PK_UserNotes\" to \"pk_user_notes\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserBans\" RENAME CONSTRAINT \"PK_UserBans\" to \"pk_user_bans\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"ServerModerationSettings\" RENAME CONSTRAINT \"PK_ServerModerationSettings\" to \"pk_server_moderation_settings\"");

            migrationBuilder.RenameColumn(
                name: "Reason",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "reason");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "UserID",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "user_id");

            migrationBuilder.RenameColumn(
                name: "UpdatedAt",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "updated_at");

            migrationBuilder.RenameColumn(
                name: "ServerID",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "server_id");

            migrationBuilder.RenameColumn(
                name: "MessageID",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "message_id");

            migrationBuilder.RenameColumn(
                name: "ExpiresOn",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "expires_on");

            migrationBuilder.RenameColumn(
                name: "CreatedAt",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "created_at");

            migrationBuilder.RenameColumn(
                name: "AuthorID",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "author_id");

            migrationBuilder.RenameIndex(
                name: "IX_UserWarnings_UserID",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "ix_user_warnings_user_id");

            migrationBuilder.RenameIndex(
                name: "IX_UserWarnings_ServerID",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "ix_user_warnings_server_id");

            migrationBuilder.RenameIndex(
                name: "IX_UserWarnings_AuthorID",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "ix_user_warnings_author_id");

            migrationBuilder.RenameColumn(
                name: "Content",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "content");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "UserID",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "user_id");

            migrationBuilder.RenameColumn(
                name: "UpdatedAt",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "updated_at");

            migrationBuilder.RenameColumn(
                name: "ServerID",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "server_id");

            migrationBuilder.RenameColumn(
                name: "CreatedAt",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "created_at");

            migrationBuilder.RenameColumn(
                name: "AuthorID",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "author_id");

            migrationBuilder.RenameIndex(
                name: "IX_UserNotes_UserID",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "ix_user_notes_user_id");

            migrationBuilder.RenameIndex(
                name: "IX_UserNotes_ServerID",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "ix_user_notes_server_id");

            migrationBuilder.RenameIndex(
                name: "IX_UserNotes_AuthorID",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "ix_user_notes_author_id");

            migrationBuilder.RenameColumn(
                name: "Reason",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "reason");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "UserID",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "user_id");

            migrationBuilder.RenameColumn(
                name: "UpdatedAt",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "updated_at");

            migrationBuilder.RenameColumn(
                name: "ServerID",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "server_id");

            migrationBuilder.RenameColumn(
                name: "MessageID",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "message_id");

            migrationBuilder.RenameColumn(
                name: "ExpiresOn",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "expires_on");

            migrationBuilder.RenameColumn(
                name: "CreatedAt",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "created_at");

            migrationBuilder.RenameColumn(
                name: "AuthorID",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "author_id");

            migrationBuilder.RenameIndex(
                name: "IX_UserBans_UserID",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "ix_user_bans_user_id");

            migrationBuilder.RenameIndex(
                name: "IX_UserBans_ServerID",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "ix_user_bans_server_id");

            migrationBuilder.RenameIndex(
                name: "IX_UserBans_AuthorID",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "ix_user_bans_author_id");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "ModerationModule",
                table: "ServerModerationSettings",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "WarningThreshold",
                schema: "ModerationModule",
                table: "ServerModerationSettings",
                newName: "warning_threshold");

            migrationBuilder.RenameColumn(
                name: "ServerID",
                schema: "ModerationModule",
                table: "ServerModerationSettings",
                newName: "server_id");

            migrationBuilder.RenameColumn(
                name: "MonitoringChannel",
                schema: "ModerationModule",
                table: "ServerModerationSettings",
                newName: "monitoring_channel");

            migrationBuilder.RenameColumn(
                name: "ModerationLogChannel",
                schema: "ModerationModule",
                table: "ServerModerationSettings",
                newName: "moderation_log_channel");

            migrationBuilder.RenameIndex(
                name: "IX_ServerModerationSettings_ServerID",
                schema: "ModerationModule",
                table: "ServerModerationSettings",
                newName: "ix_server_moderation_settings_server_id");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"ServerModerationSettings\" RENAME CONSTRAINT \"fk_server_moderation_settings_servers_server_id\" to \"FK_ServerModerationSettings_Servers_ServerID\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserBans\" RENAME CONSTRAINT \"fk_user_bans_servers_server_id\" to \"FK_UserBans_Servers_ServerID\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserBans\" RENAME CONSTRAINT \"fk_user_bans_users_author_id\" to \"FK_UserBans_Users_AuthorID\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserBans\" RENAME CONSTRAINT \"fk_user_bans_users_user_id\" to \"FK_UserBans_Users_UserID\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserNotes\" RENAME CONSTRAINT \"fk_user_notes_servers_server_id\" to \"FK_UserNotes_Servers_ServerID\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserNotes\" RENAME CONSTRAINT \"fk_user_notes_users_author_id\" to \"FK_UserNotes_Users_AuthorID\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserNotes\" RENAME CONSTRAINT \"fk_user_notes_users_user_id\" to \"FK_UserNotes_Users_UserID\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserWarnings\" RENAME CONSTRAINT \"fk_user_warnings_servers_server_id\" to \"FK_UserWarnings_Servers_ServerID\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserWarnings\" RENAME CONSTRAINT \"fk_user_warnings_users_author_id\" to \"FK_UserWarnings_Users_AuthorID\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserWarnings\" RENAME CONSTRAINT \"fk_user_warnings_users_user_id\" to \"FK_UserWarnings_Users_UserID\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserWarnings\" RENAME CONSTRAINT \"pk_user_warnings\" to \"PK_UserWarnings\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserNotes\" RENAME CONSTRAINT \"pk_user_notes\" to \"PK_UserNotes\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"UserBans\" RENAME CONSTRAINT \"pk_user_bans\" to \"PK_UserBans\"");

            migrationBuilder.Sql("ALTER TABLE \"ModerationModule\".\"ServerModerationSettings\" RENAME CONSTRAINT \"pk_server_moderation_settings\" to \"PK_ServerModerationSettings\"");

            migrationBuilder.RenameColumn(
                name: "reason",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "Reason");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "user_id",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "UserID");

            migrationBuilder.RenameColumn(
                name: "updated_at",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "UpdatedAt");

            migrationBuilder.RenameColumn(
                name: "server_id",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "ServerID");

            migrationBuilder.RenameColumn(
                name: "message_id",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "MessageID");

            migrationBuilder.RenameColumn(
                name: "expires_on",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "ExpiresOn");

            migrationBuilder.RenameColumn(
                name: "created_at",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "CreatedAt");

            migrationBuilder.RenameColumn(
                name: "author_id",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "AuthorID");

            migrationBuilder.RenameIndex(
                name: "ix_user_warnings_user_id",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "IX_UserWarnings_UserID");

            migrationBuilder.RenameIndex(
                name: "ix_user_warnings_server_id",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "IX_UserWarnings_ServerID");

            migrationBuilder.RenameIndex(
                name: "ix_user_warnings_author_id",
                schema: "ModerationModule",
                table: "UserWarnings",
                newName: "IX_UserWarnings_AuthorID");

            migrationBuilder.RenameColumn(
                name: "content",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "Content");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "user_id",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "UserID");

            migrationBuilder.RenameColumn(
                name: "updated_at",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "UpdatedAt");

            migrationBuilder.RenameColumn(
                name: "server_id",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "ServerID");

            migrationBuilder.RenameColumn(
                name: "created_at",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "CreatedAt");

            migrationBuilder.RenameColumn(
                name: "author_id",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "AuthorID");

            migrationBuilder.RenameIndex(
                name: "ix_user_notes_user_id",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "IX_UserNotes_UserID");

            migrationBuilder.RenameIndex(
                name: "ix_user_notes_server_id",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "IX_UserNotes_ServerID");

            migrationBuilder.RenameIndex(
                name: "ix_user_notes_author_id",
                schema: "ModerationModule",
                table: "UserNotes",
                newName: "IX_UserNotes_AuthorID");

            migrationBuilder.RenameColumn(
                name: "reason",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "Reason");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "user_id",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "UserID");

            migrationBuilder.RenameColumn(
                name: "updated_at",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "UpdatedAt");

            migrationBuilder.RenameColumn(
                name: "server_id",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "ServerID");

            migrationBuilder.RenameColumn(
                name: "message_id",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "MessageID");

            migrationBuilder.RenameColumn(
                name: "expires_on",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "ExpiresOn");

            migrationBuilder.RenameColumn(
                name: "created_at",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "CreatedAt");

            migrationBuilder.RenameColumn(
                name: "author_id",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "AuthorID");

            migrationBuilder.RenameIndex(
                name: "ix_user_bans_user_id",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "IX_UserBans_UserID");

            migrationBuilder.RenameIndex(
                name: "ix_user_bans_server_id",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "IX_UserBans_ServerID");

            migrationBuilder.RenameIndex(
                name: "ix_user_bans_author_id",
                schema: "ModerationModule",
                table: "UserBans",
                newName: "IX_UserBans_AuthorID");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "ModerationModule",
                table: "ServerModerationSettings",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "warning_threshold",
                schema: "ModerationModule",
                table: "ServerModerationSettings",
                newName: "WarningThreshold");

            migrationBuilder.RenameColumn(
                name: "server_id",
                schema: "ModerationModule",
                table: "ServerModerationSettings",
                newName: "ServerID");

            migrationBuilder.RenameColumn(
                name: "monitoring_channel",
                schema: "ModerationModule",
                table: "ServerModerationSettings",
                newName: "MonitoringChannel");

            migrationBuilder.RenameColumn(
                name: "moderation_log_channel",
                schema: "ModerationModule",
                table: "ServerModerationSettings",
                newName: "ModerationLogChannel");

            migrationBuilder.RenameIndex(
                name: "ix_server_moderation_settings_server_id",
                schema: "ModerationModule",
                table: "ServerModerationSettings",
                newName: "IX_ServerModerationSettings_ServerID");
        }
    }
}
