// <auto-generated />

#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective

using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DIGOS.Ambassador.Plugins.Kinks.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class FixNullableModelFields : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserKinks_Kinks_KinkID",
                schema: "KinkModule",
                table: "UserKinks");

            migrationBuilder.DropForeignKey(
                name: "FK_UserKinks_Users_UserID",
                schema: "KinkModule",
                table: "UserKinks");

            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:PostgresExtension:fuzzystrmatch", ",,");

            migrationBuilder.AlterColumn<long>(
                name: "UserID",
                schema: "KinkModule",
                table: "UserKinks",
                type: "bigint",
                nullable: false,
                defaultValue: 0L,
                oldClrType: typeof(long),
                oldType: "bigint",
                oldNullable: true);

            migrationBuilder.AlterColumn<long>(
                name: "KinkID",
                schema: "KinkModule",
                table: "UserKinks",
                type: "bigint",
                nullable: false,
                defaultValue: 0L,
                oldClrType: typeof(long),
                oldType: "bigint",
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_UserKinks_Kinks_KinkID",
                schema: "KinkModule",
                table: "UserKinks",
                column: "KinkID",
                principalSchema: "KinkModule",
                principalTable: "Kinks",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_UserKinks_Users_UserID",
                schema: "KinkModule",
                table: "UserKinks",
                column: "UserID",
                principalSchema: "Core",
                principalTable: "Users",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserKinks_Kinks_KinkID",
                schema: "KinkModule",
                table: "UserKinks");

            migrationBuilder.DropForeignKey(
                name: "FK_UserKinks_Users_UserID",
                schema: "KinkModule",
                table: "UserKinks");

            migrationBuilder.AlterDatabase()
                .OldAnnotation("Npgsql:PostgresExtension:fuzzystrmatch", ",,");

            migrationBuilder.AlterColumn<long>(
                name: "UserID",
                schema: "KinkModule",
                table: "UserKinks",
                type: "bigint",
                nullable: true,
                oldClrType: typeof(long),
                oldType: "bigint");

            migrationBuilder.AlterColumn<long>(
                name: "KinkID",
                schema: "KinkModule",
                table: "UserKinks",
                type: "bigint",
                nullable: true,
                oldClrType: typeof(long),
                oldType: "bigint");

            migrationBuilder.AddForeignKey(
                name: "FK_UserKinks_Kinks_KinkID",
                schema: "KinkModule",
                table: "UserKinks",
                column: "KinkID",
                principalSchema: "KinkModule",
                principalTable: "Kinks",
                principalColumn: "ID");

            migrationBuilder.AddForeignKey(
                name: "FK_UserKinks_Users_UserID",
                schema: "KinkModule",
                table: "UserKinks",
                column: "UserID",
                principalSchema: "Core",
                principalTable: "Users",
                principalColumn: "ID");
        }
    }
}

