// <auto-generated />

#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective

using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DIGOS.Ambassador.Plugins.Permissions.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class UseSnakeCase : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"PermissionModule\".\"UserPermissions\" RENAME CONSTRAINT \"PK_UserPermissions\" to \"pk_user_permissions\"");

            migrationBuilder.Sql("ALTER TABLE \"PermissionModule\".\"RolePermissions\" RENAME CONSTRAINT \"PK_RolePermissions\" to \"pk_role_permissions\"");

            migrationBuilder.RenameColumn(
                name: "Target",
                schema: "PermissionModule",
                table: "UserPermissions",
                newName: "target");

            migrationBuilder.RenameColumn(
                name: "Permission",
                schema: "PermissionModule",
                table: "UserPermissions",
                newName: "permission");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "PermissionModule",
                table: "UserPermissions",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "UserID",
                schema: "PermissionModule",
                table: "UserPermissions",
                newName: "user_id");

            migrationBuilder.RenameColumn(
                name: "ServerID",
                schema: "PermissionModule",
                table: "UserPermissions",
                newName: "server_id");

            migrationBuilder.RenameColumn(
                name: "IsGranted",
                schema: "PermissionModule",
                table: "UserPermissions",
                newName: "is_granted");

            migrationBuilder.RenameColumn(
                name: "Target",
                schema: "PermissionModule",
                table: "RolePermissions",
                newName: "target");

            migrationBuilder.RenameColumn(
                name: "Permission",
                schema: "PermissionModule",
                table: "RolePermissions",
                newName: "permission");

            migrationBuilder.RenameColumn(
                name: "ID",
                schema: "PermissionModule",
                table: "RolePermissions",
                newName: "id");

            migrationBuilder.RenameColumn(
                name: "RoleID",
                schema: "PermissionModule",
                table: "RolePermissions",
                newName: "role_id");

            migrationBuilder.RenameColumn(
                name: "IsGranted",
                schema: "PermissionModule",
                table: "RolePermissions",
                newName: "is_granted");

            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:PostgresExtension:fuzzystrmatch", ",,");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"PermissionModule\".\"UserPermissions\" RENAME CONSTRAINT \"pk_user_permissions\" to \"PK_UserPermissions\"");

            migrationBuilder.Sql("ALTER TABLE \"PermissionModule\".\"RolePermissions\" RENAME CONSTRAINT \"pk_role_permissions\" to \"PK_RolePermissions\"");

            migrationBuilder.RenameColumn(
                name: "target",
                schema: "PermissionModule",
                table: "UserPermissions",
                newName: "Target");

            migrationBuilder.RenameColumn(
                name: "permission",
                schema: "PermissionModule",
                table: "UserPermissions",
                newName: "Permission");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "PermissionModule",
                table: "UserPermissions",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "user_id",
                schema: "PermissionModule",
                table: "UserPermissions",
                newName: "UserID");

            migrationBuilder.RenameColumn(
                name: "server_id",
                schema: "PermissionModule",
                table: "UserPermissions",
                newName: "ServerID");

            migrationBuilder.RenameColumn(
                name: "is_granted",
                schema: "PermissionModule",
                table: "UserPermissions",
                newName: "IsGranted");

            migrationBuilder.RenameColumn(
                name: "target",
                schema: "PermissionModule",
                table: "RolePermissions",
                newName: "Target");

            migrationBuilder.RenameColumn(
                name: "permission",
                schema: "PermissionModule",
                table: "RolePermissions",
                newName: "Permission");

            migrationBuilder.RenameColumn(
                name: "id",
                schema: "PermissionModule",
                table: "RolePermissions",
                newName: "ID");

            migrationBuilder.RenameColumn(
                name: "role_id",
                schema: "PermissionModule",
                table: "RolePermissions",
                newName: "RoleID");

            migrationBuilder.RenameColumn(
                name: "is_granted",
                schema: "PermissionModule",
                table: "RolePermissions",
                newName: "IsGranted");

            migrationBuilder.AlterDatabase()
                .OldAnnotation("Npgsql:PostgresExtension:fuzzystrmatch", ",,");
        }
    }
}
