// <auto-generated />

#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective

using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DIGOS.Ambassador.Plugins.Autorole.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class ConfigureCascade : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserChannelStatistics_UserServerStatistics_UserServerStatis~",
                schema: "AutoroleModule",
                table: "UserChannelStatistics");

            migrationBuilder.DropForeignKey(
                name: "FK_UserServerStatistics_UserStatistics_UserStatisticsID",
                schema: "AutoroleModule",
                table: "UserServerStatistics");

            migrationBuilder.AddForeignKey(
                name: "FK_UserChannelStatistics_UserServerStatistics_UserServerStatis~",
                schema: "AutoroleModule",
                table: "UserChannelStatistics",
                column: "UserServerStatisticsID",
                principalSchema: "AutoroleModule",
                principalTable: "UserServerStatistics",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_UserServerStatistics_UserStatistics_UserStatisticsID",
                schema: "AutoroleModule",
                table: "UserServerStatistics",
                column: "UserStatisticsID",
                principalSchema: "AutoroleModule",
                principalTable: "UserStatistics",
                principalColumn: "ID",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserChannelStatistics_UserServerStatistics_UserServerStatis~",
                schema: "AutoroleModule",
                table: "UserChannelStatistics");

            migrationBuilder.DropForeignKey(
                name: "FK_UserServerStatistics_UserStatistics_UserStatisticsID",
                schema: "AutoroleModule",
                table: "UserServerStatistics");

            migrationBuilder.AddForeignKey(
                name: "FK_UserChannelStatistics_UserServerStatistics_UserServerStatis~",
                schema: "AutoroleModule",
                table: "UserChannelStatistics",
                column: "UserServerStatisticsID",
                principalSchema: "AutoroleModule",
                principalTable: "UserServerStatistics",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_UserServerStatistics_UserStatistics_UserStatisticsID",
                schema: "AutoroleModule",
                table: "UserServerStatistics",
                column: "UserStatisticsID",
                principalSchema: "AutoroleModule",
                principalTable: "UserStatistics",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);
        }
    }
}

