// <auto-generated />

#pragma warning disable CS1591
// ReSharper disable RedundantArgumentDefaultValue
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantUsingDirective

using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DIGOS.Ambassador.Plugins.Autorole.Migrations
{
    [ExcludeFromCodeCoverage]
    public partial class AddAutoroleConfirmations : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AutoroleConfirmations",
                schema: "AutoroleModule",
                columns: table => new
                {
                    ID = table.Column<long>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    AutoroleID = table.Column<long>(nullable: false),
                    UserID = table.Column<long>(nullable: false),
                    IsConfirmed = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AutoroleConfirmations", x => x.ID);
                    table.ForeignKey(
                        name: "FK_AutoroleConfirmations_AutoroleConfigurations_AutoroleID",
                        column: x => x.AutoroleID,
                        principalSchema: "AutoroleModule",
                        principalTable: "AutoroleConfigurations",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AutoroleConfirmations_Users_UserID",
                        column: x => x.UserID,
                        principalSchema: "Core",
                        principalTable: "Users",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AutoroleConfirmations_AutoroleID",
                schema: "AutoroleModule",
                table: "AutoroleConfirmations",
                column: "AutoroleID");

            migrationBuilder.CreateIndex(
                name: "IX_AutoroleConfirmations_UserID",
                schema: "AutoroleModule",
                table: "AutoroleConfirmations",
                column: "UserID");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AutoroleConfirmations",
                schema: "AutoroleModule");
        }
    }
}

